easy_admin:
    site_name: 'ToutLux Admin'
    design:
        brand_color: '#2c3e50'
        menu:
            - { route: 'admin_dashboard', label: 'Dashboard', icon: 'fa fa-home' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'fa fa-users' }
            - { entity: 'House', label: 'Annonces', icon: 'fa fa-home' }
            - { entity: 'Message', label: 'Messages', icon: 'fa fa-envelope' }
            - { entity: 'EmailLog', label: 'Logs Email', icon: 'fa fa-paper-plane' }

    dashboards:
        - App\Controller\Admin\DashboardController

    crud_controllers:
        - App\Controller\Admin\UserCrudController
        - App\Controller\Admin\HouseCrudController
        - App\Controller\Admin\MessageCrudController
        - App\Controller\Admin\EmailLogCrudController
