api_platform:
    title: 'TOUTLUX API'
    version: '1.0.0'
    description: 'API for TOUTLUX Mobile Application'

    openapi:
        contact:
            name: API Support
            email: support@toutlux.com
        license:
            name: Proprietary
        termsOfService: 'https://toutlux.com/terms'
        swagger_ui_extra_configuration:
            persistAuthorization: true
            docExpansion: list
            defaultModelsExpandDepth: 1
            filter: true
            showExtensions: true
            showCommonExtensions: true

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        formats:
            json: ['application/json']
            jsonld: ['application/ld+json']

    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        Symfony\Component\Validator\Exception\ValidationFailedException: 422
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
        Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
        Symfony\Component\Security\Core\Exception\AuthenticationException: 401

    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']

    patch_formats:
        json: ['application/merge-patch+json']

    collection:
        exists_parameter_name: 'exists'
        order: 'ASC'
        order_parameter_name: 'order'
        order_nulls_comparison: null
        pagination:
            enabled: true
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
            partial_parameter_name: 'partial'

    http_cache:
        public: true
        invalidation:
            enabled: false

    doctrine_mongodb_odm:
        enabled: false

    mercure:
        enabled: false

    graphql:
        enabled: false

    elasticsearch:
        enabled: false

    maker:
        enabled: true
