gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    user_provider: security.user.provider.concrete.app_user_provider
    ttl: 2592000 # 30 days
    ttl_update: true
    firewall: api
    user_identity_field: email
    single_use: true
    token_parameter_name: refreshToken
    manager_type: orm
