parameters:
    app.url: '%env(APP_URL)%'
    app.name: '%env(APP_NAME)%'
    app.upload_max_size: '%env(int:UPLOAD_MAX_SIZE)%'
    app.mobile_url: '%env(MOBILE_APP_URL)%'
    app.email.from_address: '%env(EMAIL_FROM_ADDRESS)%'
    app.email.from_name: '%env(EMAIL_FROM_NAME)%'
    app.email.admin: '%env(ADMIN_NOTIFICATION_EMAIL)%'
    app.admin.default_email: '%env(DEFAULT_ADMIN_EMAIL)%'
    app.admin.default_password: '%env(DEFAULT_ADMIN_PASSWORD)%'
    app.upload_root_dir: '%kernel.project_dir%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # Controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    # Normalizers with baseUrl injection
    App\Serializer\MediaObjectNormalizer:
        arguments:
            $baseUrl: '%app.url%'
        tags:
            - { name: 'serializer.normalizer', priority: 64 }

    App\Serializer\PropertyImageNormalizer:
        arguments:
            $baseUrl: '%app.url%'
        tags:
            - { name: 'serializer.normalizer', priority: 64 }

    App\Serializer\UserContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            $decorated: '@.inner'


    # Event Listeners
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\EventListener\JWTDecodedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\EventListener\ExceptionListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -50 }

    App\EventListener\CorsListener:
        arguments:
            $corsAllowOrigin: '%env(CORS_ALLOW_ORIGIN)%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }


    # Event Subscribers
    App\EventSubscriber\DocumentSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventSubscriber\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber }


    # Doctrine Extensions
    App\Doctrine\Extension\CurrentUserExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }


    # State Providers/Processors for API Platform 4.1
    App\State\PropertyStateProvider:
        tags: ['api_platform.state_provider']
    App\State\UserStateProvider:
        tags: ['api_platform.state_provider']
    App\State\PropertyStateProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'
    App\State\UserStateProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'
    App\State\PropertyFilterExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }


    # Validators
    App\Validator\UniqueEmailValidator:
        tags:
            - { name: validator.constraint_validator }

    App\Validator\ValidDocumentValidator:
        tags:
            - { name: validator.constraint_validator }

    App\Validator\ValidationGroups\UserValidationGroupsGenerator:
        tags:
            - { name: 'api_platform.validation_groups_generator' }


    # Commands with parameters
    App\Command\CreateAdminCommand:
        arguments:
            $defaultEmail: '%app.admin.default_email%'
            $defaultPassword: '%app.admin.default_password%'


    # Services with specific configuration
    App\Service\NotificationService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $messageBus: '@messenger.bus.default'
            $logger: '@logger'

    App\Service\Auth\JWTService:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            $jwtTTL: '%env(int:JWT_TTL)%'

    App\Service\Auth\GoogleAuthService:
        arguments:
            $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'

    App\Service\Email\EmailService:
        arguments:
            $environment: '%kernel.environment%'

    App\Service\Upload\FileUploadService:
        arguments:
            $uploadsDirectory: '%kernel.project_dir%/public/uploads'

    App\Service\Upload\ImageOptimizationService:
        arguments:
            $logger: '@logger'

    App\Service\Message\MessageValidationService:
        arguments:
            $logger: '@logger'

    App\Service\Auth\EmailVerificationService:
        arguments:
            $verifyEmailHelper: '@SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface'
            $emailService: '@App\Service\Email\EmailService'
            $userRepository: '@App\Repository\UserRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $urlGenerator: '@router'

    App\Service\Email\WelcomeEmailService:
        arguments:
            $emailService: '@App\Service\Email\EmailService'
            $emailVerificationService: '@App\Service\Auth\EmailVerificationService'
            $notificationService: '@App\Service\Email\NotificationEmailService'

    App\Service\Document\DocumentValidationService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $notificationService: '@App\Service\Email\NotificationEmailService'
            $trustScoreCalculator: '@App\Service\Document\TrustScoreCalculator'
            $validator: '@validator'
            $logger: '@logger'
