parameters:
    app.url: '%env(APP_URL)%'
    app.name: '%env(APP_NAME)%'
    app.upload_max_size: '%env(int:UPLOAD_MAX_SIZE)%'
    app.mobile_url: '%env(MOBILE_APP_URL)%'
    app.email.from_address: '%env(EMAIL_FROM_ADDRESS)%'
    app.email.from_name: '%env(EMAIL_FROM_NAME)%'
    app.email.admin: '%env(ADMIN_NOTIFICATION_EMAIL)%'
    app.admin.default_email: '%env(DEFAULT_ADMIN_EMAIL)%'
    app.admin.default_password: '%env(DEFAULT_ADMIN_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Normalizers with baseUrl injection
    App\Serializer\MediaObjectNormalizer:
        arguments:
            $baseUrl: '%app.url%'
        tags:
            - { name: 'serializer.normalizer', priority: 64 }

    App\Serializer\PropertyImageNormalizer:
        arguments:
            $baseUrl: '%app.url%'
        tags:
            - { name: 'serializer.normalizer', priority: 64 }

    # User Context Builder
    App\Serializer\UserContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            $decorated: '@.inner'

    # Event Listeners
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\EventListener\JWTDecodedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -50 }

    # Event Subscribers (autoconfigured)
    App\EventSubscriber\:
        resource: '../src/EventSubscriber/'

    # Doctrine Extensions
    App\Doctrine\Extension\CurrentUserExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }

    # Validators
    App\Validator\UniqueEmailValidator:
        tags:
            - { name: validator.constraint_validator }

    App\Validator\ValidDocumentValidator:
        tags:
            - { name: validator.constraint_validator }

    # Commands with parameters
    App\Command\CreateAdminCommand:
        arguments:
            $defaultEmail: '%app.admin.default_email%'
            $defaultPassword: '%app.admin.default_password%'

    # Services
    App\Service\NotificationService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $messageBus: '@messenger.bus.default'

    # Validation Groups Generator
    App\Validator\ValidationGroups\UserValidationGroupsGenerator:
        tags:
            - { name: 'api_platform.validation_groups_generator' }
