# API Routes
api_auth_login:
    path: /api/auth/login
    methods: POST
    controller: App\Controller\Api\AuthController::login

api_auth_refresh:
    path: /api/auth/refresh
    methods: POST
    controller: App\Controller\Api\AuthController::refresh

api_auth_logout:
    path: /api/auth/logout
    methods: POST
    controller: App\Controller\Api\AuthController::logout

api_auth_google:
    path: /api/auth/google
    methods: POST
    controller: App\Controller\Api\GoogleAuthController::authenticate

api_verify_email:
    path: /api/auth/verify-email/{token}
    methods: GET
    controller: App\Controller\Api\AuthController::verifyEmail
    requirements:
        token: '[A-Za-z0-9-_]+'

api_resend_verification:
    path: /api/auth/resend-verification
    methods: POST
    controller: App\Controller\Api\AuthController::resendVerification

api_profile_update:
    path: /api/profile
    methods: [PUT, PATCH]
    controller: App\Controller\Api\ProfileController::update

api_profile_documents:
    path: /api/profile/documents
    methods: POST
    controller: App\Controller\Api\DocumentValidationController::upload

api_messages_send:
    path: /api/messages
    methods: POST
    controller: App\Controller\Api\MessageController::send

api_messages_list:
    path: /api/messages
    methods: GET
    controller: App\Controller\Api\MessageController::list

api_messages_thread:
    path: /api/messages/thread/{id}
    methods: GET
    controller: App\Controller\Api\MessageController::thread
    requirements:
        id: '\d+'
