api_platform:
    title: 'TOUTLUX API'
    version: '1.0.0'
    description: 'API for TOUTLUX Real Estate Mobile Application'
    show_webby: false

    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']

    defaults:
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 100
        pagination_client_enabled: true
        pagination_client_items_per_page: true

    exception_to_status:
        Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 400
        Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: 401
        Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    openapi:
        contact:
            name: TOUTLUX Team
            email: contact@toutlux.com
        license:
            name: MIT

    doctrine:
        enabled: true

    graphql:
        enabled: false

    mercure:
        enabled: false

    asset_package: null

    validator:
        serialize_payload_fields: []
        query_parameter_validation: true

    eager_loading:
        enabled: true
        max_joins: 30
        force_eager: true
