framework:
    cache:
        # Configuration adaptée pour serveur mutualisé
        # Utilise le système de fichiers par défaut
        app: cache.adapter.filesystem

        # System cache - utilise filesystem aussi
        system: cache.adapter.filesystem

        pools:
            # API cache
            api.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600

            # User cache
            user.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 1800
                tags: true

            # Property cache
            property.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 7200
                tags: true

            # Trust score cache
            trust_score.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400 # 24 hours

# Configuration alternative pour Redis (à décommenter si disponible)
# framework:
#     cache:
#         app: cache.adapter.redis
#         default_redis_provider: 'redis://localhost:6379'
