gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 jours
    ttl_update: true
    firewall: api
    user_provider: security.user.provider.concrete.app_user_provider

    # Options
    single_use: true # Token utilisable une seule fois
    token_parameter_name: refresh_token

    # Cookie configuration (optionnel)
    cookie:
        enabled: false

    # Retourner l'expiration
    return_expiration: true
    return_expiration_parameter_name: refresh_token_expiration
