framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(EMAIL_FROM_ADDRESS)%'
        headers:
            From: '%env(EMAIL_FROM_NAME)% <%env(EMAIL_FROM_ADDRESS)%>'
            Reply-To: '%env(EMAIL_FROM_ADDRESS)%'

when@test:
    framework:
        mailer:
            dsn: 'null://null'
