framework:
    mailer:
        # Configuration pour PlanetHoster
        # Les détails SMTP seront dans .env.local
        dsn: '%env(MAILER_DSN)%'

        # Headers par défaut
        headers:
            From: 'TOUTLUX <noreply@toutlux.com>'
            Reply-To: 'support@toutlux.com'

        # Configuration pour éviter le spam
        envelope:
            sender: 'noreply@toutlux.com'
