framework:
    messenger:
        failure_transport: failed

        transports:
            # Main async transport
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            # Failed messages transport
            failed: 'doctrine://default?queue_name=failed'

        routing:
        # Pour le moment, pas de messages asynchrones définis
        # Les emails sont envoyés de manière synchrone
        # Ajoutez vos propres messages ici quand nécessaire

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction
