framework:
    messenger:
        default_bus: messenger.bus.default

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                    delay: 1000
                    max_delay: 0

            failed: 'doctrine://default?queue_name=failed'

        failure_transport: failed

        routing:
            # Email messages
#            App\Message\SendWelcomeEmail: async
#            App\Message\SendEmailVerification: async
#            App\Message\SendDocumentValidationEmail: async
#            App\Message\SendNewMessageNotification: async
#            App\Message\SendAdminNotification: async

            # Other async tasks
#            App\Message\OptimizeImage: async
#            App\Message\CalculateTrustScore: async
#            App\Message\ProcessDocument: async

        buses:
            messenger.bus.default:
                middleware:
                    # Add validation
                    - validation
                    # Add Doctrine transaction handling
                    - doctrine_transaction

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
