security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API Authentication
        api_login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_register:
            pattern: ^/api/users/register
            stateless: true
            security: false

        api_refresh:
            pattern: ^/api/auth/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/auth/refresh

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            jwt: ~
            logout:
                path: /api/auth/logout

        # Admin panel authentication - SIMPLIFIÉ
        admin:
            pattern: ^/admin
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin_dashboard
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login
                invalidate_session: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /admin

    access_control:
        # Public API endpoints
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/google, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/properties, roles: PUBLIC_ACCESS, methods: [GET] }

        # Authenticated API endpoints
        - { path: ^/api/users/profile, roles: ROLE_USER }
        - { path: ^/api/users/\d+/profile, roles: ROLE_USER }
        - { path: ^/api/messages, roles: ROLE_USER }
        - { path: ^/api/documents, roles: ROLE_USER }
        - { path: ^/api/properties, roles: ROLE_USER, methods: [POST, PUT, PATCH, DELETE] }

        # Admin panel
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
