vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        # Avatar des utilisateurs
        user_avatar:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true

        # Images des propriétés
        property_images:
            uri_prefix: /uploads/properties
            upload_destination: '%kernel.project_dir%/public/uploads/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true

        # Documents d'identité
        identity_documents:
            uri_prefix: /uploads/documents/identity
            upload_destination: '%kernel.project_dir%/public/uploads/documents/identity'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true

        # Documents financiers
        financial_documents:
            uri_prefix: /uploads/documents/financial
            upload_destination: '%kernel.project_dir%/public/uploads/documents/financial'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true

        # Media objects génériques
        media_objects:
            uri_prefix: /uploads/media
            upload_destination: '%kernel.project_dir%/public/uploads/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
