vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        # Images de propriétés
        property_images:
            uri_prefix: /uploads/properties
            upload_destination: '%kernel.project_dir%/public/uploads/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        # Photos de profil
        user_avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # Documents d'identité
        identity_documents:
            uri_prefix: /uploads/documents/identity
            upload_destination: '%kernel.project_dir%/public/uploads/documents/identity'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # Documents financiers
        financial_documents:
            uri_prefix: /uploads/documents/financial
            upload_destination: '%kernel.project_dir%/public/uploads/documents/financial'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
